name: CustomBiomeAnnounce
version: '${project.version}'
main: org.dark.custombiomeannounce.CustomBiomeAnnounce
api-version: '1.20'
commands:
  cba:
    description: Reloads the plugin configuration
    usage: /<command> reload